site_name: CausalBench
nav:
  - Home: index.md
  - Installation: install.md
  - Quickstart: quickstart.md
  - Learn the Basics: basics.md
  - Terms: terms.md
  - Papers: papers.md

theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true


